//
// Generated by Bluespec Compiler, version 2021.12.1-27-g9a7d5e05 (build 9a7d5e05)
//
// On Mon May  2 13:45:30 IST 2022
//
//
// Ports:
// Name                         I/O  size props
// RDY_feed_inp_stream            O     1 const
// get_out_stream                 O   288 reg
// RDY_get_out_stream             O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// feed_inp_stream_a_stream       I    96
// feed_inp_stream_b_stream       I    96
// EN_feed_inp_stream             I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mat_mult_systolic(CLK,
			 RST_N,

			 feed_inp_stream_a_stream,
			 feed_inp_stream_b_stream,
			 EN_feed_inp_stream,
			 RDY_feed_inp_stream,

			 get_out_stream,
			 RDY_get_out_stream);
  input  CLK;
  input  RST_N;

  // action method feed_inp_stream
  input  [95 : 0] feed_inp_stream_a_stream;
  input  [95 : 0] feed_inp_stream_b_stream;
  input  EN_feed_inp_stream;
  output RDY_feed_inp_stream;

  // value method get_out_stream
  output [287 : 0] get_out_stream;
  output RDY_get_out_stream;

  // signals for module outputs
  wire [287 : 0] get_out_stream;
  wire RDY_feed_inp_stream, RDY_get_out_stream;

  // register rg_inp_a_0
  reg [31 : 0] rg_inp_a_0;
  wire [31 : 0] rg_inp_a_0$D_IN;
  wire rg_inp_a_0$EN;

  // register rg_inp_a_1
  reg [31 : 0] rg_inp_a_1;
  wire [31 : 0] rg_inp_a_1$D_IN;
  wire rg_inp_a_1$EN;

  // register rg_inp_a_2
  reg [31 : 0] rg_inp_a_2;
  wire [31 : 0] rg_inp_a_2$D_IN;
  wire rg_inp_a_2$EN;

  // register rg_inp_b_0
  reg [31 : 0] rg_inp_b_0;
  wire [31 : 0] rg_inp_b_0$D_IN;
  wire rg_inp_b_0$EN;

  // register rg_inp_b_1
  reg [31 : 0] rg_inp_b_1;
  wire [31 : 0] rg_inp_b_1$D_IN;
  wire rg_inp_b_1$EN;

  // register rg_inp_b_2
  reg [31 : 0] rg_inp_b_2;
  wire [31 : 0] rg_inp_b_2$D_IN;
  wire rg_inp_b_2$EN;

  // register rg_stage0_rdy
  reg rg_stage0_rdy;
  wire rg_stage0_rdy$D_IN, rg_stage0_rdy$EN;

  // ports of submodule pe_0_0
  wire [31 : 0] pe_0_0$getA,
		pe_0_0$getB,
		pe_0_0$getC,
		pe_0_0$putA_in_a,
		pe_0_0$putB_in_b;
  wire pe_0_0$EN_putA, pe_0_0$EN_putB;

  // ports of submodule pe_0_1
  wire [31 : 0] pe_0_1$getA,
		pe_0_1$getB,
		pe_0_1$getC,
		pe_0_1$putA_in_a,
		pe_0_1$putB_in_b;
  wire pe_0_1$EN_putA, pe_0_1$EN_putB;

  // ports of submodule pe_0_2
  wire [31 : 0] pe_0_2$getB, pe_0_2$getC, pe_0_2$putA_in_a, pe_0_2$putB_in_b;
  wire pe_0_2$EN_putA, pe_0_2$EN_putB;

  // ports of submodule pe_1_0
  wire [31 : 0] pe_1_0$getA,
		pe_1_0$getB,
		pe_1_0$getC,
		pe_1_0$putA_in_a,
		pe_1_0$putB_in_b;
  wire pe_1_0$EN_putA, pe_1_0$EN_putB;

  // ports of submodule pe_1_1
  wire [31 : 0] pe_1_1$getA,
		pe_1_1$getB,
		pe_1_1$getC,
		pe_1_1$putA_in_a,
		pe_1_1$putB_in_b;
  wire pe_1_1$EN_putA, pe_1_1$EN_putB;

  // ports of submodule pe_1_2
  wire [31 : 0] pe_1_2$getB, pe_1_2$getC, pe_1_2$putA_in_a, pe_1_2$putB_in_b;
  wire pe_1_2$EN_putA, pe_1_2$EN_putB;

  // ports of submodule pe_2_0
  wire [31 : 0] pe_2_0$getA, pe_2_0$getC, pe_2_0$putA_in_a, pe_2_0$putB_in_b;
  wire pe_2_0$EN_putA, pe_2_0$EN_putB;

  // ports of submodule pe_2_1
  wire [31 : 0] pe_2_1$getA, pe_2_1$getC, pe_2_1$putA_in_a, pe_2_1$putB_in_b;
  wire pe_2_1$EN_putA, pe_2_1$EN_putB;

  // ports of submodule pe_2_2
  wire [31 : 0] pe_2_2$getC, pe_2_2$putA_in_a, pe_2_2$putB_in_b;
  wire pe_2_2$EN_putA, pe_2_2$EN_putB;

  // declarations used by system tasks
  // synopsys translate_off
  reg [63 : 0] v__h11457;
  reg [63 : 0] v__h2366;
  reg [63 : 0] v__h3211;
  reg [63 : 0] v__h4322;
  reg [63 : 0] v__h5076;
  reg [63 : 0] v__h5955;
  reg [63 : 0] v__h6709;
  // synopsys translate_on

  // remaining internal signals
  wire [97 : 0] _0_CONCAT_IF_SEXT_IF_wr_inp_a_0_whas_THEN_wr_in_ETC___d32,
		_0_CONCAT_IF_SEXT_IF_wr_inp_a_0_whas_THEN_wr_in_ETC___d35,
		_0_CONCAT_IF_SEXT_IF_wr_inp_a_0_whas_THEN_wr_in_ETC___d43,
		_0_CONCAT_IF_SEXT_IF_wr_inp_a_0_whas_THEN_wr_in_ETC___d52,
		_0_CONCAT_IF_SEXT_IF_wr_inp_a_0_whas_THEN_wr_in_ETC___d61,
		_0_CONCAT_IF_SEXT_IF_wr_inp_a_1_whas__39_THEN_w_ETC___d165,
		_0_CONCAT_IF_SEXT_IF_wr_inp_a_1_whas__39_THEN_w_ETC___d168,
		_0_CONCAT_IF_SEXT_IF_wr_inp_a_1_whas__39_THEN_w_ETC___d176,
		_0_CONCAT_IF_SEXT_IF_wr_inp_a_1_whas__39_THEN_w_ETC___d185,
		_0_CONCAT_IF_SEXT_IF_wr_inp_a_1_whas__39_THEN_w_ETC___d194,
		_0_CONCAT_IF_SEXT_IF_wr_inp_a_2_whas__72_THEN_w_ETC___d298,
		_0_CONCAT_IF_SEXT_IF_wr_inp_a_2_whas__72_THEN_w_ETC___d301,
		_0_CONCAT_IF_SEXT_IF_wr_inp_a_2_whas__72_THEN_w_ETC___d309,
		_0_CONCAT_IF_SEXT_IF_wr_inp_a_2_whas__72_THEN_w_ETC___d318,
		_0_CONCAT_IF_SEXT_IF_wr_inp_a_2_whas__72_THEN_w_ETC___d327,
		_0_CONCAT_IF_SEXT_IF_wr_inp_b_0_whas__1_THEN_wr_ETC___d100,
		_0_CONCAT_IF_SEXT_IF_wr_inp_b_0_whas__1_THEN_wr_ETC___d108,
		_0_CONCAT_IF_SEXT_IF_wr_inp_b_0_whas__1_THEN_wr_ETC___d117,
		_0_CONCAT_IF_SEXT_IF_wr_inp_b_0_whas__1_THEN_wr_ETC___d126,
		_0_CONCAT_IF_SEXT_IF_wr_inp_b_0_whas__1_THEN_wr_ETC___d97,
		_0_CONCAT_IF_SEXT_IF_wr_inp_b_1_whas__04_THEN_w_ETC___d230,
		_0_CONCAT_IF_SEXT_IF_wr_inp_b_1_whas__04_THEN_w_ETC___d233,
		_0_CONCAT_IF_SEXT_IF_wr_inp_b_1_whas__04_THEN_w_ETC___d241,
		_0_CONCAT_IF_SEXT_IF_wr_inp_b_1_whas__04_THEN_w_ETC___d250,
		_0_CONCAT_IF_SEXT_IF_wr_inp_b_1_whas__04_THEN_w_ETC___d259,
		_0_CONCAT_IF_SEXT_IF_wr_inp_b_2_whas__37_THEN_w_ETC___d363,
		_0_CONCAT_IF_SEXT_IF_wr_inp_b_2_whas__37_THEN_w_ETC___d366,
		_0_CONCAT_IF_SEXT_IF_wr_inp_b_2_whas__37_THEN_w_ETC___d374,
		_0_CONCAT_IF_SEXT_IF_wr_inp_b_2_whas__37_THEN_w_ETC___d383,
		_0_CONCAT_IF_SEXT_IF_wr_inp_b_2_whas__37_THEN_w_ETC___d392,
		_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr_inp_a_0_ETC___d38,
		_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr_inp_a_1_ETC___d171,
		_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr_inp_a_2_ETC___d304,
		_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr_inp_b_0_ETC___d103,
		_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr_inp_b_1_ETC___d236,
		_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr_inp_b_2_ETC___d369,
		_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr__ETC___d112,
		_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr__ETC___d180,
		_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr__ETC___d245,
		_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr__ETC___d313,
		_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr__ETC___d378,
		_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr__ETC___d47,
		_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d121,
		_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d189,
		_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d254,
		_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d322,
		_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d387,
		_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d56,
		_10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT__ETC___d130,
		_10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT__ETC___d198,
		_10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT__ETC___d263,
		_10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT__ETC___d331,
		_10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT__ETC___d396,
		_10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT__ETC___d65;
  wire [48 : 0] digit__h2734,
		digit__h2808,
		digit__h2897,
		digit__h2986,
		digit__h3075,
		digit__h3556,
		digit__h3623,
		digit__h3712,
		digit__h3801,
		digit__h3890,
		digit__h4606,
		digit__h4673,
		digit__h4762,
		digit__h4851,
		digit__h4940,
		digit__h5347,
		digit__h5414,
		digit__h5503,
		digit__h5592,
		digit__h5681,
		digit__h6239,
		digit__h6306,
		digit__h6395,
		digit__h6484,
		digit__h6573,
		digit__h6980,
		digit__h7047,
		digit__h7136,
		digit__h7225,
		digit__h7314,
		tx045_MINUS_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_I_ETC__q33,
		tx073_MINUS_10_MUL_10_MUL_10_MUL_10_MUL_0_CONC_ETC__q11,
		tx134_MINUS_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_ETC__q34,
		tx223_MINUS_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CO_ETC__q35,
		tx304_MINUS_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_I_ETC__q28,
		tx312_MINUS_10_MUL_10_MUL_10_MUL_10_MUL_0_CONC_ETC__q36,
		tx393_MINUS_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_ETC__q29,
		tx412_MINUS_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_I_ETC__q23,
		tx482_MINUS_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CO_ETC__q30,
		tx501_MINUS_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_ETC__q24,
		tx571_MINUS_10_MUL_10_MUL_10_MUL_10_MUL_0_CONC_ETC__q31,
		tx590_MINUS_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CO_ETC__q25,
		tx621_MINUS_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_I_ETC__q13,
		tx671_MINUS_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_I_ETC__q18,
		tx679_MINUS_10_MUL_10_MUL_10_MUL_10_MUL_0_CONC_ETC__q26,
		tx710_MINUS_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_ETC__q14,
		tx760_MINUS_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_ETC__q19,
		tx799_MINUS_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CO_ETC__q15,
		tx806_MINUS_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_I_ETC__q8,
		tx849_MINUS_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CO_ETC__q20,
		tx888_MINUS_10_MUL_10_MUL_10_MUL_10_MUL_0_CONC_ETC__q16,
		tx895_MINUS_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_ETC__q9,
		tx938_MINUS_10_MUL_10_MUL_10_MUL_10_MUL_0_CONC_ETC__q21,
		tx984_MINUS_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CO_ETC__q10,
		tx__h2806,
		tx__h2895,
		tx__h2984,
		tx__h3073,
		tx__h3621,
		tx__h3710,
		tx__h3799,
		tx__h3888,
		tx__h4671,
		tx__h4760,
		tx__h4849,
		tx__h4938,
		tx__h5412,
		tx__h5501,
		tx__h5590,
		tx__h5679,
		tx__h6304,
		tx__h6393,
		tx__h6482,
		tx__h6571,
		tx__h7045,
		tx__h7134,
		tx__h7223,
		tx__h7312,
		y__h2954,
		y__h3043,
		y__h3132,
		y__h3769,
		y__h3858,
		y__h3947,
		y__h4819,
		y__h4908,
		y__h4997,
		y__h5560,
		y__h5649,
		y__h5738,
		y__h6452,
		y__h6541,
		y__h6630,
		y__h7193,
		y__h7282,
		y__h7371;
  wire [31 : 0] feed_inp_stream_a_stream_BITS_31_TO_0__q1,
		feed_inp_stream_a_stream_BITS_63_TO_32__q3,
		feed_inp_stream_a_stream_BITS_95_TO_64__q5,
		feed_inp_stream_b_stream_BITS_31_TO_0__q2,
		feed_inp_stream_b_stream_BITS_63_TO_32__q4,
		feed_inp_stream_b_stream_BITS_95_TO_64__q6;
  wire [16 : 0] SEXT_IF_wr_inp_a_0_whas_THEN_wr_inp_a_0_wget_B_ETC___d10,
		SEXT_IF_wr_inp_a_1_whas__39_THEN_wr_inp_a_1_wg_ETC___d143,
		SEXT_IF_wr_inp_a_2_whas__72_THEN_wr_inp_a_2_wg_ETC___d276,
		SEXT_IF_wr_inp_b_0_whas__1_THEN_wr_inp_b_0_wge_ETC___d75,
		SEXT_IF_wr_inp_b_1_whas__04_THEN_wr_inp_b_1_wg_ETC___d208,
		SEXT_IF_wr_inp_b_2_whas__37_THEN_wr_inp_b_2_wg_ETC___d341;
  wire [15 : 0] IF_EN_feed_inp_stream_THEN_feed_inp_stream_a_s_ETC__q17,
		IF_EN_feed_inp_stream_THEN_feed_inp_stream_a_s_ETC__q27,
		IF_EN_feed_inp_stream_THEN_feed_inp_stream_a_s_ETC__q7,
		IF_EN_feed_inp_stream_THEN_feed_inp_stream_b_s_ETC__q12,
		IF_EN_feed_inp_stream_THEN_feed_inp_stream_b_s_ETC__q22,
		IF_EN_feed_inp_stream_THEN_feed_inp_stream_b_s_ETC__q32,
		fpart__h2419,
		fpart__h3262,
		fpart__h4375,
		fpart__h5127,
		fpart__h6008,
		fpart__h6760,
		x__h2764,
		x__h3586,
		x__h4636,
		x__h5377,
		x__h6269,
		x__h7010,
		y_avValue_snd__h2698,
		y_avValue_snd__h3520,
		y_avValue_snd__h4570,
		y_avValue_snd__h5311,
		y_avValue_snd__h6203,
		y_avValue_snd__h6944;

  // action method feed_inp_stream
  assign RDY_feed_inp_stream = 1'd1 ;

  // value method get_out_stream
  assign get_out_stream =
	     { pe_2_2$getC,
	       pe_2_1$getC,
	       pe_2_0$getC,
	       pe_1_2$getC,
	       pe_1_1$getC,
	       pe_1_0$getC,
	       pe_0_2$getC,
	       pe_0_1$getC,
	       pe_0_0$getC } ;
  assign RDY_get_out_stream = 1'd1 ;

  // submodule pe_0_0
  mk_pe pe_0_0(.CLK(CLK),
	       .RST_N(RST_N),
	       .putA_in_a(pe_0_0$putA_in_a),
	       .putB_in_b(pe_0_0$putB_in_b),
	       .EN_putA(pe_0_0$EN_putA),
	       .EN_putB(pe_0_0$EN_putB),
	       .RDY_putA(),
	       .RDY_putB(),
	       .getA(pe_0_0$getA),
	       .RDY_getA(),
	       .getB(pe_0_0$getB),
	       .RDY_getB(),
	       .getC(pe_0_0$getC),
	       .RDY_getC());

  // submodule pe_0_1
  mk_pe pe_0_1(.CLK(CLK),
	       .RST_N(RST_N),
	       .putA_in_a(pe_0_1$putA_in_a),
	       .putB_in_b(pe_0_1$putB_in_b),
	       .EN_putA(pe_0_1$EN_putA),
	       .EN_putB(pe_0_1$EN_putB),
	       .RDY_putA(),
	       .RDY_putB(),
	       .getA(pe_0_1$getA),
	       .RDY_getA(),
	       .getB(pe_0_1$getB),
	       .RDY_getB(),
	       .getC(pe_0_1$getC),
	       .RDY_getC());

  // submodule pe_0_2
  mk_pe pe_0_2(.CLK(CLK),
	       .RST_N(RST_N),
	       .putA_in_a(pe_0_2$putA_in_a),
	       .putB_in_b(pe_0_2$putB_in_b),
	       .EN_putA(pe_0_2$EN_putA),
	       .EN_putB(pe_0_2$EN_putB),
	       .RDY_putA(),
	       .RDY_putB(),
	       .getA(),
	       .RDY_getA(),
	       .getB(pe_0_2$getB),
	       .RDY_getB(),
	       .getC(pe_0_2$getC),
	       .RDY_getC());

  // submodule pe_1_0
  mk_pe pe_1_0(.CLK(CLK),
	       .RST_N(RST_N),
	       .putA_in_a(pe_1_0$putA_in_a),
	       .putB_in_b(pe_1_0$putB_in_b),
	       .EN_putA(pe_1_0$EN_putA),
	       .EN_putB(pe_1_0$EN_putB),
	       .RDY_putA(),
	       .RDY_putB(),
	       .getA(pe_1_0$getA),
	       .RDY_getA(),
	       .getB(pe_1_0$getB),
	       .RDY_getB(),
	       .getC(pe_1_0$getC),
	       .RDY_getC());

  // submodule pe_1_1
  mk_pe pe_1_1(.CLK(CLK),
	       .RST_N(RST_N),
	       .putA_in_a(pe_1_1$putA_in_a),
	       .putB_in_b(pe_1_1$putB_in_b),
	       .EN_putA(pe_1_1$EN_putA),
	       .EN_putB(pe_1_1$EN_putB),
	       .RDY_putA(),
	       .RDY_putB(),
	       .getA(pe_1_1$getA),
	       .RDY_getA(),
	       .getB(pe_1_1$getB),
	       .RDY_getB(),
	       .getC(pe_1_1$getC),
	       .RDY_getC());

  // submodule pe_1_2
  mk_pe pe_1_2(.CLK(CLK),
	       .RST_N(RST_N),
	       .putA_in_a(pe_1_2$putA_in_a),
	       .putB_in_b(pe_1_2$putB_in_b),
	       .EN_putA(pe_1_2$EN_putA),
	       .EN_putB(pe_1_2$EN_putB),
	       .RDY_putA(),
	       .RDY_putB(),
	       .getA(),
	       .RDY_getA(),
	       .getB(pe_1_2$getB),
	       .RDY_getB(),
	       .getC(pe_1_2$getC),
	       .RDY_getC());

  // submodule pe_2_0
  mk_pe pe_2_0(.CLK(CLK),
	       .RST_N(RST_N),
	       .putA_in_a(pe_2_0$putA_in_a),
	       .putB_in_b(pe_2_0$putB_in_b),
	       .EN_putA(pe_2_0$EN_putA),
	       .EN_putB(pe_2_0$EN_putB),
	       .RDY_putA(),
	       .RDY_putB(),
	       .getA(pe_2_0$getA),
	       .RDY_getA(),
	       .getB(),
	       .RDY_getB(),
	       .getC(pe_2_0$getC),
	       .RDY_getC());

  // submodule pe_2_1
  mk_pe pe_2_1(.CLK(CLK),
	       .RST_N(RST_N),
	       .putA_in_a(pe_2_1$putA_in_a),
	       .putB_in_b(pe_2_1$putB_in_b),
	       .EN_putA(pe_2_1$EN_putA),
	       .EN_putB(pe_2_1$EN_putB),
	       .RDY_putA(),
	       .RDY_putB(),
	       .getA(pe_2_1$getA),
	       .RDY_getA(),
	       .getB(),
	       .RDY_getB(),
	       .getC(pe_2_1$getC),
	       .RDY_getC());

  // submodule pe_2_2
  mk_pe pe_2_2(.CLK(CLK),
	       .RST_N(RST_N),
	       .putA_in_a(pe_2_2$putA_in_a),
	       .putB_in_b(pe_2_2$putB_in_b),
	       .EN_putA(pe_2_2$EN_putA),
	       .EN_putB(pe_2_2$EN_putB),
	       .RDY_putA(),
	       .RDY_putB(),
	       .getA(),
	       .RDY_getA(),
	       .getB(),
	       .RDY_getB(),
	       .getC(pe_2_2$getC),
	       .RDY_getC());

  // register rg_inp_a_0
  assign rg_inp_a_0$D_IN =
	     EN_feed_inp_stream ? feed_inp_stream_a_stream[31:0] : 32'd0 ;
  assign rg_inp_a_0$EN = EN_feed_inp_stream ;

  // register rg_inp_a_1
  assign rg_inp_a_1$D_IN =
	     EN_feed_inp_stream ? feed_inp_stream_a_stream[63:32] : 32'd0 ;
  assign rg_inp_a_1$EN = EN_feed_inp_stream ;

  // register rg_inp_a_2
  assign rg_inp_a_2$D_IN =
	     EN_feed_inp_stream ? feed_inp_stream_a_stream[95:64] : 32'd0 ;
  assign rg_inp_a_2$EN = EN_feed_inp_stream ;

  // register rg_inp_b_0
  assign rg_inp_b_0$D_IN =
	     EN_feed_inp_stream ? feed_inp_stream_b_stream[31:0] : 32'd0 ;
  assign rg_inp_b_0$EN = EN_feed_inp_stream ;

  // register rg_inp_b_1
  assign rg_inp_b_1$D_IN =
	     EN_feed_inp_stream ? feed_inp_stream_b_stream[63:32] : 32'd0 ;
  assign rg_inp_b_1$EN = EN_feed_inp_stream ;

  // register rg_inp_b_2
  assign rg_inp_b_2$D_IN =
	     EN_feed_inp_stream ? feed_inp_stream_b_stream[95:64] : 32'd0 ;
  assign rg_inp_b_2$EN = EN_feed_inp_stream ;

  // register rg_stage0_rdy
  assign rg_stage0_rdy$D_IN = EN_feed_inp_stream ;
  assign rg_stage0_rdy$EN = 1'd1 ;

  // submodule pe_0_0
  assign pe_0_0$putA_in_a = rg_inp_a_0 ;
  assign pe_0_0$putB_in_b = rg_inp_b_0 ;
  assign pe_0_0$EN_putA = rg_stage0_rdy ;
  assign pe_0_0$EN_putB = rg_stage0_rdy ;

  // submodule pe_0_1
  assign pe_0_1$putA_in_a = pe_0_0$getA ;
  assign pe_0_1$putB_in_b = rg_inp_b_1 ;
  assign pe_0_1$EN_putA = rg_stage0_rdy ;
  assign pe_0_1$EN_putB = rg_stage0_rdy ;

  // submodule pe_0_2
  assign pe_0_2$putA_in_a = pe_0_1$getA ;
  assign pe_0_2$putB_in_b = rg_inp_b_2 ;
  assign pe_0_2$EN_putA = rg_stage0_rdy ;
  assign pe_0_2$EN_putB = rg_stage0_rdy ;

  // submodule pe_1_0
  assign pe_1_0$putA_in_a = rg_inp_a_1 ;
  assign pe_1_0$putB_in_b = pe_0_0$getB ;
  assign pe_1_0$EN_putA = rg_stage0_rdy ;
  assign pe_1_0$EN_putB = rg_stage0_rdy ;

  // submodule pe_1_1
  assign pe_1_1$putA_in_a = pe_1_0$getA ;
  assign pe_1_1$putB_in_b = pe_0_1$getB ;
  assign pe_1_1$EN_putA = rg_stage0_rdy ;
  assign pe_1_1$EN_putB = rg_stage0_rdy ;

  // submodule pe_1_2
  assign pe_1_2$putA_in_a = pe_1_1$getA ;
  assign pe_1_2$putB_in_b = pe_0_2$getB ;
  assign pe_1_2$EN_putA = rg_stage0_rdy ;
  assign pe_1_2$EN_putB = rg_stage0_rdy ;

  // submodule pe_2_0
  assign pe_2_0$putA_in_a = rg_inp_a_2 ;
  assign pe_2_0$putB_in_b = pe_1_0$getB ;
  assign pe_2_0$EN_putA = rg_stage0_rdy ;
  assign pe_2_0$EN_putB = rg_stage0_rdy ;

  // submodule pe_2_1
  assign pe_2_1$putA_in_a = pe_2_0$getA ;
  assign pe_2_1$putB_in_b = pe_1_1$getB ;
  assign pe_2_1$EN_putA = rg_stage0_rdy ;
  assign pe_2_1$EN_putB = rg_stage0_rdy ;

  // submodule pe_2_2
  assign pe_2_2$putA_in_a = pe_2_1$getA ;
  assign pe_2_2$putB_in_b = pe_1_2$getB ;
  assign pe_2_2$EN_putA = rg_stage0_rdy ;
  assign pe_2_2$EN_putB = rg_stage0_rdy ;

  // remaining internal signals
  assign IF_EN_feed_inp_stream_THEN_feed_inp_stream_a_s_ETC__q17 =
	     EN_feed_inp_stream ?
	       feed_inp_stream_a_stream_BITS_63_TO_32__q3[31:16] :
	       16'd0 ;
  assign IF_EN_feed_inp_stream_THEN_feed_inp_stream_a_s_ETC__q27 =
	     EN_feed_inp_stream ?
	       feed_inp_stream_a_stream_BITS_95_TO_64__q5[31:16] :
	       16'd0 ;
  assign IF_EN_feed_inp_stream_THEN_feed_inp_stream_a_s_ETC__q7 =
	     EN_feed_inp_stream ?
	       feed_inp_stream_a_stream_BITS_31_TO_0__q1[31:16] :
	       16'd0 ;
  assign IF_EN_feed_inp_stream_THEN_feed_inp_stream_b_s_ETC__q12 =
	     EN_feed_inp_stream ?
	       feed_inp_stream_b_stream_BITS_31_TO_0__q2[31:16] :
	       16'd0 ;
  assign IF_EN_feed_inp_stream_THEN_feed_inp_stream_b_s_ETC__q22 =
	     EN_feed_inp_stream ?
	       feed_inp_stream_b_stream_BITS_63_TO_32__q4[31:16] :
	       16'd0 ;
  assign IF_EN_feed_inp_stream_THEN_feed_inp_stream_b_s_ETC__q32 =
	     EN_feed_inp_stream ?
	       feed_inp_stream_b_stream_BITS_95_TO_64__q6[31:16] :
	       16'd0 ;
  assign SEXT_IF_wr_inp_a_0_whas_THEN_wr_inp_a_0_wget_B_ETC___d10 =
	     { IF_EN_feed_inp_stream_THEN_feed_inp_stream_a_s_ETC__q7[15],
	       IF_EN_feed_inp_stream_THEN_feed_inp_stream_a_s_ETC__q7 } ;
  assign SEXT_IF_wr_inp_a_1_whas__39_THEN_wr_inp_a_1_wg_ETC___d143 =
	     { IF_EN_feed_inp_stream_THEN_feed_inp_stream_a_s_ETC__q17[15],
	       IF_EN_feed_inp_stream_THEN_feed_inp_stream_a_s_ETC__q17 } ;
  assign SEXT_IF_wr_inp_a_2_whas__72_THEN_wr_inp_a_2_wg_ETC___d276 =
	     { IF_EN_feed_inp_stream_THEN_feed_inp_stream_a_s_ETC__q27[15],
	       IF_EN_feed_inp_stream_THEN_feed_inp_stream_a_s_ETC__q27 } ;
  assign SEXT_IF_wr_inp_b_0_whas__1_THEN_wr_inp_b_0_wge_ETC___d75 =
	     { IF_EN_feed_inp_stream_THEN_feed_inp_stream_b_s_ETC__q12[15],
	       IF_EN_feed_inp_stream_THEN_feed_inp_stream_b_s_ETC__q12 } ;
  assign SEXT_IF_wr_inp_b_1_whas__04_THEN_wr_inp_b_1_wg_ETC___d208 =
	     { IF_EN_feed_inp_stream_THEN_feed_inp_stream_b_s_ETC__q22[15],
	       IF_EN_feed_inp_stream_THEN_feed_inp_stream_b_s_ETC__q22 } ;
  assign SEXT_IF_wr_inp_b_2_whas__37_THEN_wr_inp_b_2_wg_ETC___d341 =
	     { IF_EN_feed_inp_stream_THEN_feed_inp_stream_b_s_ETC__q32[15],
	       IF_EN_feed_inp_stream_THEN_feed_inp_stream_b_s_ETC__q32 } ;
  assign _0_CONCAT_IF_SEXT_IF_wr_inp_a_0_whas_THEN_wr_in_ETC___d32 =
	     { 33'd0, x__h2764 } * 49'd10 ;
  assign _0_CONCAT_IF_SEXT_IF_wr_inp_a_0_whas_THEN_wr_in_ETC___d35 =
	     { 33'd0, x__h2764 } * 49'd100 ;
  assign _0_CONCAT_IF_SEXT_IF_wr_inp_a_0_whas_THEN_wr_in_ETC___d43 =
	     { 33'd0, x__h2764 } * 49'd1000 ;
  assign _0_CONCAT_IF_SEXT_IF_wr_inp_a_0_whas_THEN_wr_in_ETC___d52 =
	     { 33'd0, x__h2764 } * 49'd10000 ;
  assign _0_CONCAT_IF_SEXT_IF_wr_inp_a_0_whas_THEN_wr_in_ETC___d61 =
	     { 33'd0, x__h2764 } * 49'd100000 ;
  assign _0_CONCAT_IF_SEXT_IF_wr_inp_a_1_whas__39_THEN_w_ETC___d165 =
	     { 33'd0, x__h4636 } * 49'd10 ;
  assign _0_CONCAT_IF_SEXT_IF_wr_inp_a_1_whas__39_THEN_w_ETC___d168 =
	     { 33'd0, x__h4636 } * 49'd100 ;
  assign _0_CONCAT_IF_SEXT_IF_wr_inp_a_1_whas__39_THEN_w_ETC___d176 =
	     { 33'd0, x__h4636 } * 49'd1000 ;
  assign _0_CONCAT_IF_SEXT_IF_wr_inp_a_1_whas__39_THEN_w_ETC___d185 =
	     { 33'd0, x__h4636 } * 49'd10000 ;
  assign _0_CONCAT_IF_SEXT_IF_wr_inp_a_1_whas__39_THEN_w_ETC___d194 =
	     { 33'd0, x__h4636 } * 49'd100000 ;
  assign _0_CONCAT_IF_SEXT_IF_wr_inp_a_2_whas__72_THEN_w_ETC___d298 =
	     { 33'd0, x__h6269 } * 49'd10 ;
  assign _0_CONCAT_IF_SEXT_IF_wr_inp_a_2_whas__72_THEN_w_ETC___d301 =
	     { 33'd0, x__h6269 } * 49'd100 ;
  assign _0_CONCAT_IF_SEXT_IF_wr_inp_a_2_whas__72_THEN_w_ETC___d309 =
	     { 33'd0, x__h6269 } * 49'd1000 ;
  assign _0_CONCAT_IF_SEXT_IF_wr_inp_a_2_whas__72_THEN_w_ETC___d318 =
	     { 33'd0, x__h6269 } * 49'd10000 ;
  assign _0_CONCAT_IF_SEXT_IF_wr_inp_a_2_whas__72_THEN_w_ETC___d327 =
	     { 33'd0, x__h6269 } * 49'd100000 ;
  assign _0_CONCAT_IF_SEXT_IF_wr_inp_b_0_whas__1_THEN_wr_ETC___d100 =
	     { 33'd0, x__h3586 } * 49'd100 ;
  assign _0_CONCAT_IF_SEXT_IF_wr_inp_b_0_whas__1_THEN_wr_ETC___d108 =
	     { 33'd0, x__h3586 } * 49'd1000 ;
  assign _0_CONCAT_IF_SEXT_IF_wr_inp_b_0_whas__1_THEN_wr_ETC___d117 =
	     { 33'd0, x__h3586 } * 49'd10000 ;
  assign _0_CONCAT_IF_SEXT_IF_wr_inp_b_0_whas__1_THEN_wr_ETC___d126 =
	     { 33'd0, x__h3586 } * 49'd100000 ;
  assign _0_CONCAT_IF_SEXT_IF_wr_inp_b_0_whas__1_THEN_wr_ETC___d97 =
	     { 33'd0, x__h3586 } * 49'd10 ;
  assign _0_CONCAT_IF_SEXT_IF_wr_inp_b_1_whas__04_THEN_w_ETC___d230 =
	     { 33'd0, x__h5377 } * 49'd10 ;
  assign _0_CONCAT_IF_SEXT_IF_wr_inp_b_1_whas__04_THEN_w_ETC___d233 =
	     { 33'd0, x__h5377 } * 49'd100 ;
  assign _0_CONCAT_IF_SEXT_IF_wr_inp_b_1_whas__04_THEN_w_ETC___d241 =
	     { 33'd0, x__h5377 } * 49'd1000 ;
  assign _0_CONCAT_IF_SEXT_IF_wr_inp_b_1_whas__04_THEN_w_ETC___d250 =
	     { 33'd0, x__h5377 } * 49'd10000 ;
  assign _0_CONCAT_IF_SEXT_IF_wr_inp_b_1_whas__04_THEN_w_ETC___d259 =
	     { 33'd0, x__h5377 } * 49'd100000 ;
  assign _0_CONCAT_IF_SEXT_IF_wr_inp_b_2_whas__37_THEN_w_ETC___d363 =
	     { 33'd0, x__h7010 } * 49'd10 ;
  assign _0_CONCAT_IF_SEXT_IF_wr_inp_b_2_whas__37_THEN_w_ETC___d366 =
	     { 33'd0, x__h7010 } * 49'd100 ;
  assign _0_CONCAT_IF_SEXT_IF_wr_inp_b_2_whas__37_THEN_w_ETC___d374 =
	     { 33'd0, x__h7010 } * 49'd1000 ;
  assign _0_CONCAT_IF_SEXT_IF_wr_inp_b_2_whas__37_THEN_w_ETC___d383 =
	     { 33'd0, x__h7010 } * 49'd10000 ;
  assign _0_CONCAT_IF_SEXT_IF_wr_inp_b_2_whas__37_THEN_w_ETC___d392 =
	     { 33'd0, x__h7010 } * 49'd100000 ;
  assign _10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr_inp_a_0_ETC___d38 =
	     49'd10 * digit__h2734 ;
  assign _10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr_inp_a_1_ETC___d171 =
	     49'd10 * digit__h4606 ;
  assign _10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr_inp_a_2_ETC___d304 =
	     49'd10 * digit__h6239 ;
  assign _10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr_inp_b_0_ETC___d103 =
	     49'd10 * digit__h3556 ;
  assign _10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr_inp_b_1_ETC___d236 =
	     49'd10 * digit__h5347 ;
  assign _10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr_inp_b_2_ETC___d369 =
	     49'd10 * digit__h6980 ;
  assign _10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr__ETC___d112 =
	     49'd10 * y__h3769 ;
  assign _10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr__ETC___d180 =
	     49'd10 * y__h4819 ;
  assign _10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr__ETC___d245 =
	     49'd10 * y__h5560 ;
  assign _10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr__ETC___d313 =
	     49'd10 * y__h6452 ;
  assign _10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr__ETC___d378 =
	     49'd10 * y__h7193 ;
  assign _10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr__ETC___d47 =
	     49'd10 * y__h2954 ;
  assign _10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d121 =
	     49'd10 * y__h3858 ;
  assign _10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d189 =
	     49'd10 * y__h4908 ;
  assign _10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d254 =
	     49'd10 * y__h5649 ;
  assign _10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d322 =
	     49'd10 * y__h6541 ;
  assign _10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d387 =
	     49'd10 * y__h7282 ;
  assign _10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d56 =
	     49'd10 * y__h3043 ;
  assign _10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT__ETC___d130 =
	     49'd10 * y__h3947 ;
  assign _10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT__ETC___d198 =
	     49'd10 * y__h4997 ;
  assign _10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT__ETC___d263 =
	     49'd10 * y__h5738 ;
  assign _10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT__ETC___d331 =
	     49'd10 * y__h6630 ;
  assign _10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT__ETC___d396 =
	     49'd10 * y__h7371 ;
  assign _10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT__ETC___d65 =
	     49'd10 * y__h3132 ;
  assign digit__h2734 =
	     { 45'd0,
	       _0_CONCAT_IF_SEXT_IF_wr_inp_a_0_whas_THEN_wr_in_ETC___d32[19:16] } ;
  assign digit__h2808 =
	     { 45'd0,
	       tx806_MINUS_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_I_ETC__q8[3:0] } ;
  assign digit__h2897 =
	     { 45'd0,
	       tx895_MINUS_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_ETC__q9[3:0] } ;
  assign digit__h2986 =
	     { 45'd0,
	       tx984_MINUS_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CO_ETC__q10[3:0] } ;
  assign digit__h3075 =
	     { 45'd0,
	       tx073_MINUS_10_MUL_10_MUL_10_MUL_10_MUL_0_CONC_ETC__q11[3:0] } ;
  assign digit__h3556 =
	     { 45'd0,
	       _0_CONCAT_IF_SEXT_IF_wr_inp_b_0_whas__1_THEN_wr_ETC___d97[19:16] } ;
  assign digit__h3623 =
	     { 45'd0,
	       tx621_MINUS_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_I_ETC__q13[3:0] } ;
  assign digit__h3712 =
	     { 45'd0,
	       tx710_MINUS_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_ETC__q14[3:0] } ;
  assign digit__h3801 =
	     { 45'd0,
	       tx799_MINUS_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CO_ETC__q15[3:0] } ;
  assign digit__h3890 =
	     { 45'd0,
	       tx888_MINUS_10_MUL_10_MUL_10_MUL_10_MUL_0_CONC_ETC__q16[3:0] } ;
  assign digit__h4606 =
	     { 45'd0,
	       _0_CONCAT_IF_SEXT_IF_wr_inp_a_1_whas__39_THEN_w_ETC___d165[19:16] } ;
  assign digit__h4673 =
	     { 45'd0,
	       tx671_MINUS_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_I_ETC__q18[3:0] } ;
  assign digit__h4762 =
	     { 45'd0,
	       tx760_MINUS_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_ETC__q19[3:0] } ;
  assign digit__h4851 =
	     { 45'd0,
	       tx849_MINUS_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CO_ETC__q20[3:0] } ;
  assign digit__h4940 =
	     { 45'd0,
	       tx938_MINUS_10_MUL_10_MUL_10_MUL_10_MUL_0_CONC_ETC__q21[3:0] } ;
  assign digit__h5347 =
	     { 45'd0,
	       _0_CONCAT_IF_SEXT_IF_wr_inp_b_1_whas__04_THEN_w_ETC___d230[19:16] } ;
  assign digit__h5414 =
	     { 45'd0,
	       tx412_MINUS_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_I_ETC__q23[3:0] } ;
  assign digit__h5503 =
	     { 45'd0,
	       tx501_MINUS_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_ETC__q24[3:0] } ;
  assign digit__h5592 =
	     { 45'd0,
	       tx590_MINUS_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CO_ETC__q25[3:0] } ;
  assign digit__h5681 =
	     { 45'd0,
	       tx679_MINUS_10_MUL_10_MUL_10_MUL_10_MUL_0_CONC_ETC__q26[3:0] } ;
  assign digit__h6239 =
	     { 45'd0,
	       _0_CONCAT_IF_SEXT_IF_wr_inp_a_2_whas__72_THEN_w_ETC___d298[19:16] } ;
  assign digit__h6306 =
	     { 45'd0,
	       tx304_MINUS_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_I_ETC__q28[3:0] } ;
  assign digit__h6395 =
	     { 45'd0,
	       tx393_MINUS_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_ETC__q29[3:0] } ;
  assign digit__h6484 =
	     { 45'd0,
	       tx482_MINUS_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CO_ETC__q30[3:0] } ;
  assign digit__h6573 =
	     { 45'd0,
	       tx571_MINUS_10_MUL_10_MUL_10_MUL_10_MUL_0_CONC_ETC__q31[3:0] } ;
  assign digit__h6980 =
	     { 45'd0,
	       _0_CONCAT_IF_SEXT_IF_wr_inp_b_2_whas__37_THEN_w_ETC___d363[19:16] } ;
  assign digit__h7047 =
	     { 45'd0,
	       tx045_MINUS_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_I_ETC__q33[3:0] } ;
  assign digit__h7136 =
	     { 45'd0,
	       tx134_MINUS_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_ETC__q34[3:0] } ;
  assign digit__h7225 =
	     { 45'd0,
	       tx223_MINUS_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CO_ETC__q35[3:0] } ;
  assign digit__h7314 =
	     { 45'd0,
	       tx312_MINUS_10_MUL_10_MUL_10_MUL_10_MUL_0_CONC_ETC__q36[3:0] } ;
  assign feed_inp_stream_a_stream_BITS_31_TO_0__q1 =
	     feed_inp_stream_a_stream[31:0] ;
  assign feed_inp_stream_a_stream_BITS_63_TO_32__q3 =
	     feed_inp_stream_a_stream[63:32] ;
  assign feed_inp_stream_a_stream_BITS_95_TO_64__q5 =
	     feed_inp_stream_a_stream[95:64] ;
  assign feed_inp_stream_b_stream_BITS_31_TO_0__q2 =
	     feed_inp_stream_b_stream[31:0] ;
  assign feed_inp_stream_b_stream_BITS_63_TO_32__q4 =
	     feed_inp_stream_b_stream[63:32] ;
  assign feed_inp_stream_b_stream_BITS_95_TO_64__q6 =
	     feed_inp_stream_b_stream[95:64] ;
  assign fpart__h2419 =
	     EN_feed_inp_stream ?
	       feed_inp_stream_a_stream_BITS_31_TO_0__q1[15:0] :
	       16'd0 ;
  assign fpart__h3262 =
	     EN_feed_inp_stream ?
	       feed_inp_stream_b_stream_BITS_31_TO_0__q2[15:0] :
	       16'd0 ;
  assign fpart__h4375 =
	     EN_feed_inp_stream ?
	       feed_inp_stream_a_stream_BITS_63_TO_32__q3[15:0] :
	       16'd0 ;
  assign fpart__h5127 =
	     EN_feed_inp_stream ?
	       feed_inp_stream_b_stream_BITS_63_TO_32__q4[15:0] :
	       16'd0 ;
  assign fpart__h6008 =
	     EN_feed_inp_stream ?
	       feed_inp_stream_a_stream_BITS_95_TO_64__q5[15:0] :
	       16'd0 ;
  assign fpart__h6760 =
	     EN_feed_inp_stream ?
	       feed_inp_stream_b_stream_BITS_95_TO_64__q6[15:0] :
	       16'd0 ;
  assign tx045_MINUS_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_I_ETC__q33 =
	     tx__h7045 -
	     _10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr_inp_b_2_ETC___d369[48:0] ;
  assign tx073_MINUS_10_MUL_10_MUL_10_MUL_10_MUL_0_CONC_ETC__q11 =
	     tx__h3073 -
	     _10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT__ETC___d65[48:0] ;
  assign tx134_MINUS_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_ETC__q34 =
	     tx__h7134 -
	     _10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr__ETC___d378[48:0] ;
  assign tx223_MINUS_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CO_ETC__q35 =
	     tx__h7223 -
	     _10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d387[48:0] ;
  assign tx304_MINUS_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_I_ETC__q28 =
	     tx__h6304 -
	     _10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr_inp_a_2_ETC___d304[48:0] ;
  assign tx312_MINUS_10_MUL_10_MUL_10_MUL_10_MUL_0_CONC_ETC__q36 =
	     tx__h7312 -
	     _10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT__ETC___d396[48:0] ;
  assign tx393_MINUS_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_ETC__q29 =
	     tx__h6393 -
	     _10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr__ETC___d313[48:0] ;
  assign tx412_MINUS_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_I_ETC__q23 =
	     tx__h5412 -
	     _10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr_inp_b_1_ETC___d236[48:0] ;
  assign tx482_MINUS_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CO_ETC__q30 =
	     tx__h6482 -
	     _10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d322[48:0] ;
  assign tx501_MINUS_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_ETC__q24 =
	     tx__h5501 -
	     _10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr__ETC___d245[48:0] ;
  assign tx571_MINUS_10_MUL_10_MUL_10_MUL_10_MUL_0_CONC_ETC__q31 =
	     tx__h6571 -
	     _10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT__ETC___d331[48:0] ;
  assign tx590_MINUS_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CO_ETC__q25 =
	     tx__h5590 -
	     _10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d254[48:0] ;
  assign tx621_MINUS_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_I_ETC__q13 =
	     tx__h3621 -
	     _10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr_inp_b_0_ETC___d103[48:0] ;
  assign tx671_MINUS_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_I_ETC__q18 =
	     tx__h4671 -
	     _10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr_inp_a_1_ETC___d171[48:0] ;
  assign tx679_MINUS_10_MUL_10_MUL_10_MUL_10_MUL_0_CONC_ETC__q26 =
	     tx__h5679 -
	     _10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT__ETC___d263[48:0] ;
  assign tx710_MINUS_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_ETC__q14 =
	     tx__h3710 -
	     _10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr__ETC___d112[48:0] ;
  assign tx760_MINUS_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_ETC__q19 =
	     tx__h4760 -
	     _10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr__ETC___d180[48:0] ;
  assign tx799_MINUS_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CO_ETC__q15 =
	     tx__h3799 -
	     _10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d121[48:0] ;
  assign tx806_MINUS_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_I_ETC__q8 =
	     tx__h2806 -
	     _10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr_inp_a_0_ETC___d38[48:0] ;
  assign tx849_MINUS_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CO_ETC__q20 =
	     tx__h4849 -
	     _10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d189[48:0] ;
  assign tx888_MINUS_10_MUL_10_MUL_10_MUL_10_MUL_0_CONC_ETC__q16 =
	     tx__h3888 -
	     _10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT__ETC___d130[48:0] ;
  assign tx895_MINUS_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_ETC__q9 =
	     tx__h2895 -
	     _10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr__ETC___d47[48:0] ;
  assign tx938_MINUS_10_MUL_10_MUL_10_MUL_10_MUL_0_CONC_ETC__q21 =
	     tx__h4938 -
	     _10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT__ETC___d198[48:0] ;
  assign tx984_MINUS_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CO_ETC__q10 =
	     tx__h2984 -
	     _10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d56[48:0] ;
  assign tx__h2806 =
	     { 16'd0,
	       _0_CONCAT_IF_SEXT_IF_wr_inp_a_0_whas_THEN_wr_in_ETC___d35[48:16] } ;
  assign tx__h2895 =
	     { 16'd0,
	       _0_CONCAT_IF_SEXT_IF_wr_inp_a_0_whas_THEN_wr_in_ETC___d43[48:16] } ;
  assign tx__h2984 =
	     { 16'd0,
	       _0_CONCAT_IF_SEXT_IF_wr_inp_a_0_whas_THEN_wr_in_ETC___d52[48:16] } ;
  assign tx__h3073 =
	     { 16'd0,
	       _0_CONCAT_IF_SEXT_IF_wr_inp_a_0_whas_THEN_wr_in_ETC___d61[48:16] } ;
  assign tx__h3621 =
	     { 16'd0,
	       _0_CONCAT_IF_SEXT_IF_wr_inp_b_0_whas__1_THEN_wr_ETC___d100[48:16] } ;
  assign tx__h3710 =
	     { 16'd0,
	       _0_CONCAT_IF_SEXT_IF_wr_inp_b_0_whas__1_THEN_wr_ETC___d108[48:16] } ;
  assign tx__h3799 =
	     { 16'd0,
	       _0_CONCAT_IF_SEXT_IF_wr_inp_b_0_whas__1_THEN_wr_ETC___d117[48:16] } ;
  assign tx__h3888 =
	     { 16'd0,
	       _0_CONCAT_IF_SEXT_IF_wr_inp_b_0_whas__1_THEN_wr_ETC___d126[48:16] } ;
  assign tx__h4671 =
	     { 16'd0,
	       _0_CONCAT_IF_SEXT_IF_wr_inp_a_1_whas__39_THEN_w_ETC___d168[48:16] } ;
  assign tx__h4760 =
	     { 16'd0,
	       _0_CONCAT_IF_SEXT_IF_wr_inp_a_1_whas__39_THEN_w_ETC___d176[48:16] } ;
  assign tx__h4849 =
	     { 16'd0,
	       _0_CONCAT_IF_SEXT_IF_wr_inp_a_1_whas__39_THEN_w_ETC___d185[48:16] } ;
  assign tx__h4938 =
	     { 16'd0,
	       _0_CONCAT_IF_SEXT_IF_wr_inp_a_1_whas__39_THEN_w_ETC___d194[48:16] } ;
  assign tx__h5412 =
	     { 16'd0,
	       _0_CONCAT_IF_SEXT_IF_wr_inp_b_1_whas__04_THEN_w_ETC___d233[48:16] } ;
  assign tx__h5501 =
	     { 16'd0,
	       _0_CONCAT_IF_SEXT_IF_wr_inp_b_1_whas__04_THEN_w_ETC___d241[48:16] } ;
  assign tx__h5590 =
	     { 16'd0,
	       _0_CONCAT_IF_SEXT_IF_wr_inp_b_1_whas__04_THEN_w_ETC___d250[48:16] } ;
  assign tx__h5679 =
	     { 16'd0,
	       _0_CONCAT_IF_SEXT_IF_wr_inp_b_1_whas__04_THEN_w_ETC___d259[48:16] } ;
  assign tx__h6304 =
	     { 16'd0,
	       _0_CONCAT_IF_SEXT_IF_wr_inp_a_2_whas__72_THEN_w_ETC___d301[48:16] } ;
  assign tx__h6393 =
	     { 16'd0,
	       _0_CONCAT_IF_SEXT_IF_wr_inp_a_2_whas__72_THEN_w_ETC___d309[48:16] } ;
  assign tx__h6482 =
	     { 16'd0,
	       _0_CONCAT_IF_SEXT_IF_wr_inp_a_2_whas__72_THEN_w_ETC___d318[48:16] } ;
  assign tx__h6571 =
	     { 16'd0,
	       _0_CONCAT_IF_SEXT_IF_wr_inp_a_2_whas__72_THEN_w_ETC___d327[48:16] } ;
  assign tx__h7045 =
	     { 16'd0,
	       _0_CONCAT_IF_SEXT_IF_wr_inp_b_2_whas__37_THEN_w_ETC___d366[48:16] } ;
  assign tx__h7134 =
	     { 16'd0,
	       _0_CONCAT_IF_SEXT_IF_wr_inp_b_2_whas__37_THEN_w_ETC___d374[48:16] } ;
  assign tx__h7223 =
	     { 16'd0,
	       _0_CONCAT_IF_SEXT_IF_wr_inp_b_2_whas__37_THEN_w_ETC___d383[48:16] } ;
  assign tx__h7312 =
	     { 16'd0,
	       _0_CONCAT_IF_SEXT_IF_wr_inp_b_2_whas__37_THEN_w_ETC___d392[48:16] } ;
  assign x__h2764 =
	     (SEXT_IF_wr_inp_a_0_whas_THEN_wr_inp_a_0_wget_B_ETC___d10[16] &&
	      fpart__h2419 != 16'd0) ?
	       y_avValue_snd__h2698 :
	       fpart__h2419 ;
  assign x__h3586 =
	     (SEXT_IF_wr_inp_b_0_whas__1_THEN_wr_inp_b_0_wge_ETC___d75[16] &&
	      fpart__h3262 != 16'd0) ?
	       y_avValue_snd__h3520 :
	       fpart__h3262 ;
  assign x__h4636 =
	     (SEXT_IF_wr_inp_a_1_whas__39_THEN_wr_inp_a_1_wg_ETC___d143[16] &&
	      fpart__h4375 != 16'd0) ?
	       y_avValue_snd__h4570 :
	       fpart__h4375 ;
  assign x__h5377 =
	     (SEXT_IF_wr_inp_b_1_whas__04_THEN_wr_inp_b_1_wg_ETC___d208[16] &&
	      fpart__h5127 != 16'd0) ?
	       y_avValue_snd__h5311 :
	       fpart__h5127 ;
  assign x__h6269 =
	     (SEXT_IF_wr_inp_a_2_whas__72_THEN_wr_inp_a_2_wg_ETC___d276[16] &&
	      fpart__h6008 != 16'd0) ?
	       y_avValue_snd__h6203 :
	       fpart__h6008 ;
  assign x__h7010 =
	     (SEXT_IF_wr_inp_b_2_whas__37_THEN_wr_inp_b_2_wg_ETC___d341[16] &&
	      fpart__h6760 != 16'd0) ?
	       y_avValue_snd__h6944 :
	       fpart__h6760 ;
  assign y__h2954 =
	     _10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr_inp_a_0_ETC___d38[48:0] +
	     digit__h2808 ;
  assign y__h3043 =
	     _10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr__ETC___d47[48:0] +
	     digit__h2897 ;
  assign y__h3132 =
	     _10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d56[48:0] +
	     digit__h2986 ;
  assign y__h3769 =
	     _10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr_inp_b_0_ETC___d103[48:0] +
	     digit__h3623 ;
  assign y__h3858 =
	     _10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr__ETC___d112[48:0] +
	     digit__h3712 ;
  assign y__h3947 =
	     _10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d121[48:0] +
	     digit__h3801 ;
  assign y__h4819 =
	     _10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr_inp_a_1_ETC___d171[48:0] +
	     digit__h4673 ;
  assign y__h4908 =
	     _10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr__ETC___d180[48:0] +
	     digit__h4762 ;
  assign y__h4997 =
	     _10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d189[48:0] +
	     digit__h4851 ;
  assign y__h5560 =
	     _10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr_inp_b_1_ETC___d236[48:0] +
	     digit__h5414 ;
  assign y__h5649 =
	     _10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr__ETC___d245[48:0] +
	     digit__h5503 ;
  assign y__h5738 =
	     _10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d254[48:0] +
	     digit__h5592 ;
  assign y__h6452 =
	     _10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr_inp_a_2_ETC___d304[48:0] +
	     digit__h6306 ;
  assign y__h6541 =
	     _10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr__ETC___d313[48:0] +
	     digit__h6395 ;
  assign y__h6630 =
	     _10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d322[48:0] +
	     digit__h6484 ;
  assign y__h7193 =
	     _10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr_inp_b_2_ETC___d369[48:0] +
	     digit__h7047 ;
  assign y__h7282 =
	     _10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_IF_wr__ETC___d378[48:0] +
	     digit__h7136 ;
  assign y__h7371 =
	     _10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d387[48:0] +
	     digit__h7225 ;
  assign y_avValue_snd__h2698 = 16'd0 - fpart__h2419 ;
  assign y_avValue_snd__h3520 = 16'd0 - fpart__h3262 ;
  assign y_avValue_snd__h4570 = 16'd0 - fpart__h4375 ;
  assign y_avValue_snd__h5311 = 16'd0 - fpart__h5127 ;
  assign y_avValue_snd__h6203 = 16'd0 - fpart__h6008 ;
  assign y_avValue_snd__h6944 = 16'd0 - fpart__h6760 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        rg_inp_a_0 <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rg_inp_a_1 <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rg_inp_a_2 <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rg_inp_b_0 <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rg_inp_b_1 <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rg_inp_b_2 <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rg_stage0_rdy <= `BSV_ASSIGNMENT_DELAY 1'd0;
      end
    else
      begin
        if (rg_inp_a_0$EN)
	  rg_inp_a_0 <= `BSV_ASSIGNMENT_DELAY rg_inp_a_0$D_IN;
	if (rg_inp_a_1$EN)
	  rg_inp_a_1 <= `BSV_ASSIGNMENT_DELAY rg_inp_a_1$D_IN;
	if (rg_inp_a_2$EN)
	  rg_inp_a_2 <= `BSV_ASSIGNMENT_DELAY rg_inp_a_2$D_IN;
	if (rg_inp_b_0$EN)
	  rg_inp_b_0 <= `BSV_ASSIGNMENT_DELAY rg_inp_b_0$D_IN;
	if (rg_inp_b_1$EN)
	  rg_inp_b_1 <= `BSV_ASSIGNMENT_DELAY rg_inp_b_1$D_IN;
	if (rg_inp_b_2$EN)
	  rg_inp_b_2 <= `BSV_ASSIGNMENT_DELAY rg_inp_b_2$D_IN;
	if (rg_stage0_rdy$EN)
	  rg_stage0_rdy <= `BSV_ASSIGNMENT_DELAY rg_stage0_rdy$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    rg_inp_a_0 = 32'hAAAAAAAA;
    rg_inp_a_1 = 32'hAAAAAAAA;
    rg_inp_a_2 = 32'hAAAAAAAA;
    rg_inp_b_0 = 32'hAAAAAAAA;
    rg_inp_b_1 = 32'hAAAAAAAA;
    rg_inp_b_2 = 32'hAAAAAAAA;
    rg_stage0_rdy = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream)
	begin
	  v__h11457 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream)
	$display(v__h11457, " [MULT] method feed_inp_stream reached");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream)
	begin
	  v__h2366 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream)
	$display(v__h2366,
		 " [MULT] [stage0] latching A[%d] ",
		 $signed(32'd0));
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream &&
	  SEXT_IF_wr_inp_a_0_whas_THEN_wr_inp_a_0_wget_B_ETC___d10[16] &&
	  fpart__h2419 != 16'd0 &&
	  SEXT_IF_wr_inp_a_0_whas_THEN_wr_inp_a_0_wget_B_ETC___d10 ==
	  17'd131071)
	$write("-0.");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream &&
	  SEXT_IF_wr_inp_a_0_whas_THEN_wr_inp_a_0_wget_B_ETC___d10[16] &&
	  fpart__h2419 != 16'd0 &&
	  SEXT_IF_wr_inp_a_0_whas_THEN_wr_inp_a_0_wget_B_ETC___d10 !=
	  17'd131071)
	$write("%0d.",
	       $signed(SEXT_IF_wr_inp_a_0_whas_THEN_wr_inp_a_0_wget_B_ETC___d10 +
		       17'd1));
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream &&
	  (!SEXT_IF_wr_inp_a_0_whas_THEN_wr_inp_a_0_wget_B_ETC___d10[16] ||
	   fpart__h2419 == 16'd0))
	$write("%0d.",
	       $signed(SEXT_IF_wr_inp_a_0_whas_THEN_wr_inp_a_0_wget_B_ETC___d10));
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream) $write("%0d", digit__h2734);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream) $write("%0d", digit__h2808);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream) $write("%0d", digit__h2897);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream) $write("%0d", digit__h2986);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream) $write("%0d", digit__h3075);
    if (RST_N != `BSV_RESET_VALUE) if (EN_feed_inp_stream) $display("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream)
	begin
	  v__h3211 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream)
	$display(v__h3211,
		 " [MULT] [stage0] latching B[%d] ",
		 $signed(32'd0));
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream &&
	  SEXT_IF_wr_inp_b_0_whas__1_THEN_wr_inp_b_0_wge_ETC___d75[16] &&
	  fpart__h3262 != 16'd0 &&
	  SEXT_IF_wr_inp_b_0_whas__1_THEN_wr_inp_b_0_wge_ETC___d75 ==
	  17'd131071)
	$write("-0.");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream &&
	  SEXT_IF_wr_inp_b_0_whas__1_THEN_wr_inp_b_0_wge_ETC___d75[16] &&
	  fpart__h3262 != 16'd0 &&
	  SEXT_IF_wr_inp_b_0_whas__1_THEN_wr_inp_b_0_wge_ETC___d75 !=
	  17'd131071)
	$write("%0d.",
	       $signed(SEXT_IF_wr_inp_b_0_whas__1_THEN_wr_inp_b_0_wge_ETC___d75 +
		       17'd1));
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream &&
	  (!SEXT_IF_wr_inp_b_0_whas__1_THEN_wr_inp_b_0_wge_ETC___d75[16] ||
	   fpart__h3262 == 16'd0))
	$write("%0d.",
	       $signed(SEXT_IF_wr_inp_b_0_whas__1_THEN_wr_inp_b_0_wge_ETC___d75));
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream) $write("%0d", digit__h3556);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream) $write("%0d", digit__h3623);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream) $write("%0d", digit__h3712);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream) $write("%0d", digit__h3801);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream) $write("%0d", digit__h3890);
    if (RST_N != `BSV_RESET_VALUE) if (EN_feed_inp_stream) $display("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream)
	begin
	  v__h4322 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream)
	$display(v__h4322,
		 " [MULT] [stage0] latching A[%d] ",
		 $signed(32'd1));
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream &&
	  SEXT_IF_wr_inp_a_1_whas__39_THEN_wr_inp_a_1_wg_ETC___d143[16] &&
	  fpart__h4375 != 16'd0 &&
	  SEXT_IF_wr_inp_a_1_whas__39_THEN_wr_inp_a_1_wg_ETC___d143 ==
	  17'd131071)
	$write("-0.");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream &&
	  SEXT_IF_wr_inp_a_1_whas__39_THEN_wr_inp_a_1_wg_ETC___d143[16] &&
	  fpart__h4375 != 16'd0 &&
	  SEXT_IF_wr_inp_a_1_whas__39_THEN_wr_inp_a_1_wg_ETC___d143 !=
	  17'd131071)
	$write("%0d.",
	       $signed(SEXT_IF_wr_inp_a_1_whas__39_THEN_wr_inp_a_1_wg_ETC___d143 +
		       17'd1));
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream &&
	  (!SEXT_IF_wr_inp_a_1_whas__39_THEN_wr_inp_a_1_wg_ETC___d143[16] ||
	   fpart__h4375 == 16'd0))
	$write("%0d.",
	       $signed(SEXT_IF_wr_inp_a_1_whas__39_THEN_wr_inp_a_1_wg_ETC___d143));
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream) $write("%0d", digit__h4606);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream) $write("%0d", digit__h4673);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream) $write("%0d", digit__h4762);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream) $write("%0d", digit__h4851);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream) $write("%0d", digit__h4940);
    if (RST_N != `BSV_RESET_VALUE) if (EN_feed_inp_stream) $display("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream)
	begin
	  v__h5076 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream)
	$display(v__h5076,
		 " [MULT] [stage0] latching B[%d] ",
		 $signed(32'd1));
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream &&
	  SEXT_IF_wr_inp_b_1_whas__04_THEN_wr_inp_b_1_wg_ETC___d208[16] &&
	  fpart__h5127 != 16'd0 &&
	  SEXT_IF_wr_inp_b_1_whas__04_THEN_wr_inp_b_1_wg_ETC___d208 ==
	  17'd131071)
	$write("-0.");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream &&
	  SEXT_IF_wr_inp_b_1_whas__04_THEN_wr_inp_b_1_wg_ETC___d208[16] &&
	  fpart__h5127 != 16'd0 &&
	  SEXT_IF_wr_inp_b_1_whas__04_THEN_wr_inp_b_1_wg_ETC___d208 !=
	  17'd131071)
	$write("%0d.",
	       $signed(SEXT_IF_wr_inp_b_1_whas__04_THEN_wr_inp_b_1_wg_ETC___d208 +
		       17'd1));
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream &&
	  (!SEXT_IF_wr_inp_b_1_whas__04_THEN_wr_inp_b_1_wg_ETC___d208[16] ||
	   fpart__h5127 == 16'd0))
	$write("%0d.",
	       $signed(SEXT_IF_wr_inp_b_1_whas__04_THEN_wr_inp_b_1_wg_ETC___d208));
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream) $write("%0d", digit__h5347);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream) $write("%0d", digit__h5414);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream) $write("%0d", digit__h5503);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream) $write("%0d", digit__h5592);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream) $write("%0d", digit__h5681);
    if (RST_N != `BSV_RESET_VALUE) if (EN_feed_inp_stream) $display("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream)
	begin
	  v__h5955 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream)
	$display(v__h5955,
		 " [MULT] [stage0] latching A[%d] ",
		 $signed(32'd2));
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream &&
	  SEXT_IF_wr_inp_a_2_whas__72_THEN_wr_inp_a_2_wg_ETC___d276[16] &&
	  fpart__h6008 != 16'd0 &&
	  SEXT_IF_wr_inp_a_2_whas__72_THEN_wr_inp_a_2_wg_ETC___d276 ==
	  17'd131071)
	$write("-0.");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream &&
	  SEXT_IF_wr_inp_a_2_whas__72_THEN_wr_inp_a_2_wg_ETC___d276[16] &&
	  fpart__h6008 != 16'd0 &&
	  SEXT_IF_wr_inp_a_2_whas__72_THEN_wr_inp_a_2_wg_ETC___d276 !=
	  17'd131071)
	$write("%0d.",
	       $signed(SEXT_IF_wr_inp_a_2_whas__72_THEN_wr_inp_a_2_wg_ETC___d276 +
		       17'd1));
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream &&
	  (!SEXT_IF_wr_inp_a_2_whas__72_THEN_wr_inp_a_2_wg_ETC___d276[16] ||
	   fpart__h6008 == 16'd0))
	$write("%0d.",
	       $signed(SEXT_IF_wr_inp_a_2_whas__72_THEN_wr_inp_a_2_wg_ETC___d276));
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream) $write("%0d", digit__h6239);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream) $write("%0d", digit__h6306);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream) $write("%0d", digit__h6395);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream) $write("%0d", digit__h6484);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream) $write("%0d", digit__h6573);
    if (RST_N != `BSV_RESET_VALUE) if (EN_feed_inp_stream) $display("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream)
	begin
	  v__h6709 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream)
	$display(v__h6709,
		 " [MULT] [stage0] latching B[%d] ",
		 $signed(32'd2));
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream &&
	  SEXT_IF_wr_inp_b_2_whas__37_THEN_wr_inp_b_2_wg_ETC___d341[16] &&
	  fpart__h6760 != 16'd0 &&
	  SEXT_IF_wr_inp_b_2_whas__37_THEN_wr_inp_b_2_wg_ETC___d341 ==
	  17'd131071)
	$write("-0.");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream &&
	  SEXT_IF_wr_inp_b_2_whas__37_THEN_wr_inp_b_2_wg_ETC___d341[16] &&
	  fpart__h6760 != 16'd0 &&
	  SEXT_IF_wr_inp_b_2_whas__37_THEN_wr_inp_b_2_wg_ETC___d341 !=
	  17'd131071)
	$write("%0d.",
	       $signed(SEXT_IF_wr_inp_b_2_whas__37_THEN_wr_inp_b_2_wg_ETC___d341 +
		       17'd1));
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream &&
	  (!SEXT_IF_wr_inp_b_2_whas__37_THEN_wr_inp_b_2_wg_ETC___d341[16] ||
	   fpart__h6760 == 16'd0))
	$write("%0d.",
	       $signed(SEXT_IF_wr_inp_b_2_whas__37_THEN_wr_inp_b_2_wg_ETC___d341));
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream) $write("%0d", digit__h6980);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream) $write("%0d", digit__h7047);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream) $write("%0d", digit__h7136);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream) $write("%0d", digit__h7225);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_feed_inp_stream) $write("%0d", digit__h7314);
    if (RST_N != `BSV_RESET_VALUE) if (EN_feed_inp_stream) $display("\n");
  end
  // synopsys translate_on
endmodule  // mat_mult_systolic

