webtalk_init -webtalk_dir /mnt/5a853c24-31e3-4d80-9826-512f6bd995e7/saurav/Academics/EE5332/Project/Kalman-Bhai/src/bluespec/xsim.dir/a.out.xsim/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun May  1 12:34:29 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d93a3e8c-a30f-4a2c-b79b-0a716e18c622" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "7b408ec5-7643-4def-8f31-4600d9b49dc8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "13" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2347.497 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "24.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runtime -value "105 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "115556_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3524283149 -regid "" -xml /mnt/5a853c24-31e3-4d80-9826-512f6bd995e7/saurav/Academics/EE5332/Project/Kalman-Bhai/src/bluespec/xsim.dir/a.out.xsim/webtalk/usage_statistics_ext_xsim.xml -html /mnt/5a853c24-31e3-4d80-9826-512f6bd995e7/saurav/Academics/EE5332/Project/Kalman-Bhai/src/bluespec/xsim.dir/a.out.xsim/webtalk/usage_statistics_ext_xsim.html -wdm /mnt/5a853c24-31e3-4d80-9826-512f6bd995e7/saurav/Academics/EE5332/Project/Kalman-Bhai/src/bluespec/xsim.dir/a.out.xsim/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
